/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import static java.lang.System.exit;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author OnurOkyay
 */
public class JFkvsb extends javax.swing.JFrame {
Kullanici oyuncu;
Bilgisayar Bot2;
ArrayList<Pokemon> list;
int sayac=0;
int adim=0;
int son=0;
int sayac2=0;
int sonucsayac=0;
int o=3;
int t=0;
int p=0;
 int[]dizi ;
    /**
     * Creates new form JFkvsb
     */
    public JFkvsb() {
        initComponents();
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        jButton30.setVisible(false);
        jButton31.setVisible(false);
        jButton32.setVisible(false);
        jButton33.setVisible(false);
        jButton34.setVisible(false);
        jButton35.setVisible(false);
        jButton20.setVisible(false);
        jButtonarea1.setVisible(false);
        jButtonarea2.setVisible(false);
        jButton28.setVisible(false);
        jButton29.setVisible(false);
        jButtonsonuç.setVisible(false);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        sil = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButtonarea1 = new javax.swing.JButton();
        jButtonarea2 = new javax.swing.JButton();
        jButtonsonuç = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        name.setBackground(new java.awt.Color(204, 204, 204));
        name.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(780, 300, 400, 140);

        sil.setEditable(false);
        sil.setBackground(new java.awt.Color(204, 204, 204));
        sil.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        sil.setText("Lütfen isminizi giriniz.");
        getContentPane().add(sil);
        sil.setBounds(749, 160, 470, 70);

        text1.setEditable(false);
        text1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text1.setText("KULLANICI");
        text1.setBorder(null);
        text1.setOpaque(false);
        getContentPane().add(text1);
        text1.setBounds(1320, 840, 360, 110);

        text2.setEditable(false);
        text2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text2.setText("Bilgisayar");
        text2.setAutoscrolls(false);
        text2.setBorder(null);
        text2.setOpaque(false);
        text2.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(text2);
        text2.setBounds(1310, 30, 320, 90);

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\psyduck.jpg")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(80, 290, 160, 220);

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\bulbasaur.jpg")); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(280, 290, 160, 220);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\butterfree.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 290, 160, 220);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\jigglypuf.jpg")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(700, 290, 160, 220);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\meowth.jpg")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(920, 280, 160, 230);

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\pikachu.jpg")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(80, 530, 160, 220);

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\snorlax.jpg")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(280, 530, 160, 220);

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\zubat.jpg")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(490, 530, 160, 220);

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\squirtle.jpg")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(700, 530, 160, 220);

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\charmander.jpg")); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(920, 530, 160, 220);

        jButton20.setText("Sonraki Tur");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(1770, 450, 120, 80);

        jButton30.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\squirtle.jpg")); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(390, 800, 160, 210);

        jButton31.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\jigglypuf.jpg")); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(570, 800, 150, 210);

        jButton32.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\psyduck.jpg")); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(740, 800, 160, 210);

        jButton33.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\charmander.jpg")); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(350, 20, 160, 220);

        jButton34.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\bulbasaur.jpg")); // NOI18N
        getContentPane().add(jButton34);
        jButton34.setBounds(540, 20, 160, 220);

        jButton35.setIcon(new javax.swing.ImageIcon("C:\\Users\\OnurOkyay\\Desktop\\kartlar\\meowth.jpg")); // NOI18N
        getContentPane().add(jButton35);
        jButton35.setBounds(720, 20, 160, 220);

        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(923, 803, 150, 210);

        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(1090, 803, 150, 210);

        jButtonarea1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jButtonarea1);
        jButtonarea1.setBounds(1340, 500, 250, 300);

        jButtonarea2.setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jButtonarea2);
        jButtonarea2.setBounds(1340, 140, 250, 300);

        jButtonsonuç.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sonuç.jpg"))); // NOI18N
        jButtonsonuç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsonuçActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsonuç);
        jButtonsonuç.setBounds(0, 0, 1920, 1080);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arkaplan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1910, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1910, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        sil.setVisible(false);
        
         list=new ArrayList<Pokemon>();
            Pokemon pika=new Pikachu("01","Pikachu","Elektrik");
            Pokemon bulba=new Bulbasaur("02","Bulbasaur","Çim");
            Pokemon charman=new Charmander("03","Charmander","Ateş");
            Pokemon squ=new Squirtle("04","Squirtle","Su");
            Pokemon zuba=new Zubat("05","Zubat","Hava");
            Pokemon psy=new Psyduck("06","Psyduck","Su");
            Pokemon snor=new Snorlax("07","Snorlax","Normal");
            Pokemon butter=new Butterfree("08","Butterfree","Hava");
            Pokemon jiggly=new Jigglypuff("09","Jigglypuff","Ses");
            Pokemon meow=new Meowth("10","Meowth","Normal");
            
            
            list.add(pika);
            list.add(bulba);
            list.add(charman);
            list.add(squ);
            list.add(zuba);
            list.add(psy);
            list.add(snor);
            list.add(butter);
            list.add(jiggly);
            list.add(meow);
            
        
        
        
        
        
        String username=name.getText();
        text1.setText(username);
        name.setVisible(false);
        
      
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        
      int x1,i=0;
      dizi =new int[10];
            Random  rnd=new Random();
            while(i<10){
               x1=rnd.nextInt(10);
               dizi[i]=x1;
               for(int j=0;j<i;j++){
                   if(dizi[j]==dizi[i]){
                       
                       i--;
                   }
               }
                i++;
                
            }
            
            for(int k=0;k<10;k++){
                System.out.println("--> "+dizi[k]);
            }
            
            
            
        jButton11.setIcon(new javax.swing.ImageIcon(list.get(dizi[0]).getDosyayolu()));
        jButton12.setIcon(new javax.swing.ImageIcon(list.get(dizi[1]).getDosyayolu()));
        jButton3.setIcon(new javax.swing.ImageIcon(list.get(dizi[2]).getDosyayolu()));
        jButton4.setIcon(new javax.swing.ImageIcon(list.get(dizi[3]).getDosyayolu()));
        jButton5.setIcon(new javax.swing.ImageIcon(list.get(dizi[4]).getDosyayolu()));
        jButton6.setIcon(new javax.swing.ImageIcon(list.get(dizi[5]).getDosyayolu()));
        jButton7.setIcon(new javax.swing.ImageIcon(list.get(dizi[6]).getDosyayolu()));
        jButton8.setIcon(new javax.swing.ImageIcon(list.get(dizi[7]).getDosyayolu()));
        jButton9.setIcon(new javax.swing.ImageIcon(list.get(dizi[8]).getDosyayolu()));
        jButton10.setIcon(new javax.swing.ImageIcon(list.get(dizi[9]).getDosyayolu()));
        
        
        
        System.out.println(username);
         oyuncu=new Kullanici(username, "002", 0);
         Bot2=new Bilgisayar("bilgisayar","000",0);
        

        
        
        int a,b,c;
            
            do{
                a=rnd.nextInt(10);
                b=rnd.nextInt(10);
                c=rnd.nextInt(10);
                
            }while(a==b || a==c || b==c);
            
            Bot2.KartSec(list, a, b, c);
            System.out.println(""+Bot2.liste.get(0));
            System.out.println(""+Bot2.liste.get(1));  
            System.out.println(""+Bot2.liste.get(2));
            Bot2.liste.get(0).setKullanim();
            Bot2.liste.get(1).setKullanim();
            Bot2.liste.get(2).setKullanim();
            
            
            if(list.get(dizi[0]).kullanildiMi(list.get(dizi[0]).getKullanim())){
            jButton11.setVisible(false);
        }
        
        if(list.get(dizi[1]).kullanildiMi(list.get(dizi[1]).getKullanim())){
            jButton12.setVisible(false);
        }
        
        if(list.get(dizi[2]).kullanildiMi(list.get(dizi[2]).getKullanim())){
            jButton3.setVisible(false);
        }
        
        if(list.get(dizi[3]).kullanildiMi(list.get(dizi[3]).getKullanim())){
            jButton4.setVisible(false);
        }
        
        if(list.get(dizi[4]).kullanildiMi(list.get(dizi[4]).getKullanim())){
            jButton5.setVisible(false);
        }
        
        if(list.get(dizi[5]).kullanildiMi(list.get(dizi[5]).getKullanim())){
            jButton6.setVisible(false);
        }
        
        if(list.get(dizi[6]).kullanildiMi(list.get(dizi[6]).getKullanim())){
            jButton7.setVisible(false);
        }
        
        if(list.get(dizi[7]).kullanildiMi(list.get(dizi[7]).getKullanim())){
            jButton8.setVisible(false);
        }
        
        if(list.get(dizi[8]).kullanildiMi(list.get(dizi[8]).getKullanim())){
            jButton9.setVisible(false);
        }
        
        if(list.get(dizi[9]).kullanildiMi(list.get(dizi[9]).getKullanim())){
            jButton10.setVisible(false);
        }
            
            
            
            System.out.println(""+list.get(0).getKullanim());
            System.out.println(""+list.get(1).getKullanim());
            System.out.println(""+list.get(2).getKullanim());
            System.out.println(""+list.get(3).getKullanim());
            System.out.println(""+list.get(4).getKullanim());
            System.out.println(""+list.get(5).getKullanim());
            System.out.println(""+list.get(6).getKullanim());
            System.out.println(""+list.get(7).getKullanim());
            System.out.println(""+list.get(8).getKullanim());
            System.out.println(""+list.get(9).getKullanim());
           
            System.out.println(""+list.get(0).kullanildiMi(list.get(0).getKullanim()));
            System.out.println(""+list.get(1).kullanildiMi(list.get(1).getKullanim()));
            System.out.println(""+list.get(2).kullanildiMi(list.get(2).getKullanim()));
            System.out.println(""+list.get(3).kullanildiMi(list.get(3).getKullanim()));
            System.out.println(""+list.get(4).kullanildiMi(list.get(4).getKullanim()));
            
            
           
           
           
            
            
      
      
        
        
      
    }//GEN-LAST:event_nameActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       if(sayac<3){
               
       oyuncu.liste.add(list.get(dizi[0]));
       list.get(dizi[0]).setKullanim();
       jButton11.setVisible(false);
       sayac++;
       sayac2++;
       adim++;
       }
       if(adim>2){
           adim=-1000;
           jButton20.setVisible(true);
       }
       if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        
           System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        
            o++;
        t++;
        
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[1]));
        list.get(dizi[1]).setKullanim();
        jButton12.setVisible(false);
        sayac++;
        sayac2++;
        adim++;
        }
       
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
       
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[2]));
        list.get(dizi[2]).setKullanim();
        jButton3.setVisible(false);
        sayac++;
        sayac2++;
        adim++;
        }
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(sayac<3){
        oyuncu.liste.add(list.get(dizi[3]));
       list.get(dizi[3]).setKullanim();
       jButton4.setVisible(false);
       sayac++;
       sayac2++;
       adim++;
       }
       if(adim>2){
           adim=-1000;
           jButton20.setVisible(true);
       }
       if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[4]));
        list.get(dizi[4]).setKullanim();
        jButton5.setVisible(false);
        sayac++;
        adim++;
        sayac2++;
        }
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[5]));
       list.get(dizi[5]).setKullanim();
        jButton6.setVisible(false);
        sayac++;
        sayac2++;
        adim++;
        }
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[6]));
       list.get(dizi[6]).setKullanim();
       jButton7.setVisible(false);
       sayac++;
       sayac2++;
       adim++;
        }
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[7]));
       list.get(dizi[7]).setKullanim();
        jButton8.setVisible(false);
        sayac++;
        sayac2++;
        adim++;
        }
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(sayac<3){
        oyuncu.liste.add(list.get(dizi[8]));
        list.get(dizi[8]).setKullanim();
        jButton9.setVisible(false);
        sayac++;
        sayac2++;
        adim++;
        }
        if(adim>2){
            adim=-1000;
           jButton20.setVisible(true);
       }
        if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
        p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       if(sayac<3){
        oyuncu.liste.add(list.get(dizi[9]));
        list.get(dizi[9]).setKullanim();
        jButton10.setVisible(false);
        sayac++;
        sayac2++;
        adim++;
       }
       if(adim>2){
           adim=-1000;
           jButton20.setVisible(true);
       }
       if(sayac2==5){
        jButton28.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButton28.setVisible(true);
       p++;
        if(p==2){
            o++;
        t++;
        }
        System.out.println("kart eklendi"+o);
    }
    if(sayac2==7){
        jButton29.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButton29.setVisible(true);
        o++;
        t++;
        System.out.println("kart eklendi"+o);
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // Sonraki Tur
        jButton30.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(0).getDosyayolu()));
        jButton31.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(1).getDosyayolu()));
        jButton32.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(2).getDosyayolu()));
        jButton33.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(0).getDosyayolu()));
        jButton34.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(1).getDosyayolu()));
        jButton35.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(2).getDosyayolu()));
           jButton30.setVisible(true);
           jButton31.setVisible(true);
           jButton32.setVisible(true);
           jButton33.setVisible(true);
           jButton34.setVisible(true);
           jButton35.setVisible(true);
           jButton20.setVisible(false);
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
         System.out.println("Size"+Bot2.liste.size());
        System.out.println("o nun degeri"+o);
        if(o==Bot2.liste.size() || t>=5){ 
            o--;
            t++;
            p++;
        Random rnd=new Random();
         int z=rnd.nextInt(3);
         while(Bot2.liste.get(z).kullanildiMi2(Bot2.liste.get(z).getKullanim2())){
             z=rnd.nextInt(3);
         }
         if(oyuncu.liste.get(0).getDamage()>Bot2.liste.get(z).getDamage()){
             oyuncu.setSkor();
         }
         else if(oyuncu.liste.get(0).getDamage()==Bot2.liste.get(z).getDamage()){
             
         }
         else{
             Bot2.setSkor();
         }
         oyuncu.SkorGoster();
         Bot2.SkorGoster();
         if(z==0){
             jButton33.setVisible(false);
         }
         if(z==1){
             jButton34.setVisible(false);
         }
         if(z==2){
             jButton35.setVisible(false);
         }
         Bot2.liste.get(z).setKullanim2();
         oyuncu.liste.get(0).setKullanim2();
         jButton30.setVisible(false);
         sayac--;
         
        jButtonarea1.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(0).getDosyayolu()));
        jButtonarea2.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
        
        jButtonarea1.setVisible(true);
        jButtonarea2.setVisible(true);
        int y1=0;
    if(son<2){
        y1=rnd.nextInt(10);
    while(list.get(y1).kullanildiMi(list.get(y1).getKullanim())){
        y1=rnd.nextInt(10);
    }
    }
    
    System.out.println("y1-->" +y1);
    if(son<=1){
         Bot2.liste.set(z,list.get(y1));
   
    Bot2.liste.get(z).setKullanim();
    
    son++;
    if(z==0){
             jButton33.setVisible(true);
             jButton33.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
         if(z==1){
             jButton34.setVisible(true);
              jButton34.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
             
         }
         if(z==2){
             jButton35.setVisible(true);
              jButton35.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
    }
    
    
     
         if(list.get(dizi[0]).kullanildiMi(list.get(dizi[0]).getKullanim())){
            jButton11.setVisible(false);
        }
        
        if(list.get(dizi[1]).kullanildiMi(list.get(dizi[1]).getKullanim())){
            jButton12.setVisible(false);
        }
        
        if(list.get(dizi[2]).kullanildiMi(list.get(dizi[2]).getKullanim())){
            jButton3.setVisible(false);
        }
        
        if(list.get(dizi[3]).kullanildiMi(list.get(dizi[3]).getKullanim())){
            jButton4.setVisible(false);
        }
        
        if(list.get(dizi[4]).kullanildiMi(list.get(dizi[4]).getKullanim())){
            jButton5.setVisible(false);
        }
        
        if(list.get(dizi[5]).kullanildiMi(list.get(dizi[5]).getKullanim())){
            jButton6.setVisible(false);
        }
        
        if(list.get(dizi[6]).kullanildiMi(list.get(dizi[6]).getKullanim())){
            jButton7.setVisible(false);
        }
        
        if(list.get(dizi[7]).kullanildiMi(list.get(dizi[7]).getKullanim())){
            jButton8.setVisible(false);
        }
        
        if(list.get(dizi[8]).kullanildiMi(list.get(dizi[8]).getKullanim())){
            jButton9.setVisible(false);
        }
        
        if(list.get(dizi[9]).kullanildiMi(list.get(dizi[9]).getKullanim())){
            jButton10.setVisible(false);
        }
         sayac2++;
         sonucsayac++;
         if(sonucsayac==5){
             jButtonsonuç.setVisible(true);
         }
        
    }//GEN-LAST:event_jButton30ActionPerformed
}
    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
         System.out.println("Size"+Bot2.liste.size());
        System.out.println("o nun degeri"+o);
        if(o==Bot2.liste.size() || t>=5){
            o--;
            t++;
              p++;
        Random rnd=new Random();
         int z=rnd.nextInt(3);
         while(Bot2.liste.get(z).kullanildiMi2(Bot2.liste.get(z).getKullanim2())){
             z=rnd.nextInt(3);
         }
         if(oyuncu.liste.get(1).getDamage()>Bot2.liste.get(z).getDamage()){
             oyuncu.setSkor();
         }
         else if(oyuncu.liste.get(1).getDamage()==Bot2.liste.get(z).getDamage()){
             
         }
         else{
             Bot2.setSkor();
         }
         oyuncu.SkorGoster();
         Bot2.SkorGoster();
         if(z==0){
             jButton33.setVisible(false);
         }
         if(z==1){
             jButton34.setVisible(false);
         }
         if(z==2){
             jButton35.setVisible(false);
         }
        Bot2.liste.get(z).setKullanim2();
         oyuncu.liste.get(1).setKullanim2();
         sayac--;
         jButton31.setVisible(false);
          jButtonarea1.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(1).getDosyayolu()));
        jButtonarea2.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
        jButtonarea1.setVisible(true);
        jButtonarea2.setVisible(true);
         
         int y1=0;
    if(son<2){
        y1=rnd.nextInt(10);
    while(list.get(y1).kullanildiMi(list.get(y1).getKullanim())){
        y1=rnd.nextInt(10);
        
    }
    }
    
    System.out.println("y1-->" +y1);
    if(son<=1){
         Bot2.liste.set(z,list.get(y1));
   
    Bot2.liste.get(z).setKullanim();
   
    son++;
    if(z==0){
             jButton33.setVisible(true);
             jButton33.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
         if(z==1){
             jButton34.setVisible(true);
              jButton34.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
             
         }
         if(z==2){
             jButton35.setVisible(true);
              jButton35.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
    }
    
         
    
         if(list.get(dizi[0]).kullanildiMi(list.get(dizi[0]).getKullanim())){
            jButton11.setVisible(false);
        }
        
        if(list.get(dizi[1]).kullanildiMi(list.get(dizi[1]).getKullanim())){
            jButton12.setVisible(false);
        }
        
        if(list.get(dizi[2]).kullanildiMi(list.get(dizi[2]).getKullanim())){
            jButton3.setVisible(false);
        }
        
        if(list.get(dizi[3]).kullanildiMi(list.get(dizi[3]).getKullanim())){
            jButton4.setVisible(false);
        }
        
        if(list.get(dizi[4]).kullanildiMi(list.get(dizi[4]).getKullanim())){
            jButton5.setVisible(false);
        }
        
        if(list.get(dizi[5]).kullanildiMi(list.get(dizi[5]).getKullanim())){
            jButton6.setVisible(false);
        }
        
        if(list.get(dizi[6]).kullanildiMi(list.get(dizi[6]).getKullanim())){
            jButton7.setVisible(false);
        }
        
        if(list.get(dizi[7]).kullanildiMi(list.get(dizi[7]).getKullanim())){
            jButton8.setVisible(false);
        }
        
        if(list.get(dizi[8]).kullanildiMi(list.get(dizi[8]).getKullanim())){
            jButton9.setVisible(false);
        }
        
        if(list.get(dizi[9]).kullanildiMi(list.get(dizi[9]).getKullanim())){
            jButton10.setVisible(false);
        }
        
        sayac2++;
        sonucsayac++;
         if(sonucsayac==5){
             jButtonsonuç.setVisible(true);
         }
    }//GEN-LAST:event_jButton31ActionPerformed
}
    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
         System.out.println("Size"+Bot2.liste.size());
        System.out.println("o nun degeri"+o);
        if(o==Bot2.liste.size() || t>=5){
        o--;
        t++;
        p++;
             Random rnd=new Random();
         int z=rnd.nextInt(3);
         while(Bot2.liste.get(z).kullanildiMi2(Bot2.liste.get(z).getKullanim2())){
             z=rnd.nextInt(3);
         }
         if(oyuncu.liste.get(2).getDamage()>Bot2.liste.get(z).getDamage()){
             oyuncu.setSkor();
         }
         else if(oyuncu.liste.get(2).getDamage()==Bot2.liste.get(z).getDamage()){
             
         }
         else{
             Bot2.setSkor();
             
         }
         oyuncu.SkorGoster();
         Bot2.SkorGoster();
         Bot2.liste.get(z).setKullanim2();
         oyuncu.liste.get(2).setKullanim2();
         if(z==0){
             jButton33.setVisible(false);
         }
         if(z==1){
             jButton34.setVisible(false);
         }
         if(z==2){
             jButton35.setVisible(false);
         }
         sayac--;
         jButton32.setVisible(false);
          jButtonarea1.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(2).getDosyayolu()));
        jButtonarea2.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
        jButtonarea1.setVisible(true);
        jButtonarea2.setVisible(true);
        
        int y1=0;
    if(son<2){
        y1=rnd.nextInt(10);
    while(list.get(y1).kullanildiMi(list.get(y1).getKullanim())){
        y1=rnd.nextInt(10);
    }
    }
    
    System.out.println("y1-->" +y1);
    if(son<=1){
         Bot2.liste.set(z,list.get(y1));
   
    Bot2.liste.get(z).setKullanim();
    
    son++;
    if(z==0){
             jButton33.setVisible(true);
             jButton33.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
         if(z==1){
             jButton34.setVisible(true);
              jButton34.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
             
         }
         if(z==2){
             jButton35.setVisible(true);
              jButton35.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
   }
     
  
    
         if(list.get(dizi[0]).kullanildiMi(list.get(dizi[0]).getKullanim())){
            jButton11.setVisible(false);
        }
        
        if(list.get(dizi[1]).kullanildiMi(list.get(dizi[1]).getKullanim())){
            jButton12.setVisible(false);
        }
        
        if(list.get(dizi[2]).kullanildiMi(list.get(dizi[2]).getKullanim())){
            jButton3.setVisible(false);
        }
        
        if(list.get(dizi[3]).kullanildiMi(list.get(dizi[3]).getKullanim())){
            jButton4.setVisible(false);
        }
        
        if(list.get(dizi[4]).kullanildiMi(list.get(dizi[4]).getKullanim())){
            jButton5.setVisible(false);
        }
        
        if(list.get(dizi[5]).kullanildiMi(list.get(dizi[5]).getKullanim())){
            jButton6.setVisible(false);
        }
        
        if(list.get(dizi[6]).kullanildiMi(list.get(dizi[6]).getKullanim())){
            jButton7.setVisible(false);
        }
        
        if(list.get(dizi[7]).kullanildiMi(list.get(dizi[7]).getKullanim())){
            jButton8.setVisible(false);
        }
        
        if(list.get(dizi[8]).kullanildiMi(list.get(dizi[8]).getKullanim())){
            jButton9.setVisible(false);
        }
        
        if(list.get(dizi[9]).kullanildiMi(list.get(dizi[9]).getKullanim())){
            jButton10.setVisible(false);
        }
    sayac2++;
        sonucsayac++;
         if(sonucsayac==5){
             jButtonsonuç.setVisible(true);
         }
    }//GEN-LAST:event_jButton32ActionPerformed
}
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        System.out.println("Size"+Bot2.liste.size());
        System.out.println("o nun degeri"+o);
        if(o==Bot2.liste.size() || t>=5){
        o--;
        t++;
          p++;
             Random rnd=new Random();
         int z=rnd.nextInt(3);
         while(Bot2.liste.get(z).kullanildiMi2(Bot2.liste.get(z).getKullanim2())){
             z=rnd.nextInt(3);
         }
         if(oyuncu.liste.get(3).getDamage()>Bot2.liste.get(z).getDamage()){
             oyuncu.setSkor();
         }
         else if(oyuncu.liste.get(3).getDamage()==Bot2.liste.get(z).getDamage()){
             
         }
         else{
             Bot2.setSkor();
             
         }
         oyuncu.SkorGoster();
         Bot2.SkorGoster();
         Bot2.liste.get(z).setKullanim2();
         oyuncu.liste.get(3).setKullanim2();
         if(z==0){
             jButton33.setVisible(false);
         }
         if(z==1){
             jButton34.setVisible(false);
         }
         if(z==2){
             jButton35.setVisible(false);
         }
         sayac--;
         jButton28.setVisible(false);
          jButtonarea1.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(3).getDosyayolu()));
        jButtonarea2.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
        jButtonarea1.setVisible(true);
        jButtonarea2.setVisible(true);
        
        int y1=0;
    if(son<2){
        y1=rnd.nextInt(10);
    while(list.get(y1).kullanildiMi(list.get(y1).getKullanim())){
        y1=rnd.nextInt(10);
    }
    }
    
    System.out.println("y1-->" +y1);
    if(son<=1){
         Bot2.liste.set(z,list.get(y1));
   
    Bot2.liste.get(z).setKullanim();
    
    son++;
    if(z==0){
             jButton33.setVisible(true);
             jButton33.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
         if(z==1){
             jButton34.setVisible(true);
              jButton34.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
             
         }
         if(z==2){
             jButton35.setVisible(true);
              jButton35.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
   }
     
  
    
         if(list.get(dizi[0]).kullanildiMi(list.get(dizi[0]).getKullanim())){
            jButton11.setVisible(false);
        }
        
        if(list.get(dizi[1]).kullanildiMi(list.get(dizi[1]).getKullanim())){
            jButton12.setVisible(false);
        }
        
        if(list.get(dizi[2]).kullanildiMi(list.get(dizi[2]).getKullanim())){
            jButton3.setVisible(false);
        }
        
        if(list.get(dizi[3]).kullanildiMi(list.get(dizi[3]).getKullanim())){
            jButton4.setVisible(false);
        }
        
        if(list.get(dizi[4]).kullanildiMi(list.get(dizi[4]).getKullanim())){
            jButton5.setVisible(false);
        }
        
        if(list.get(dizi[5]).kullanildiMi(list.get(dizi[5]).getKullanim())){
            jButton6.setVisible(false);
        }
        
        if(list.get(dizi[6]).kullanildiMi(list.get(dizi[6]).getKullanim())){
            jButton7.setVisible(false);
        }
        
        if(list.get(dizi[7]).kullanildiMi(list.get(dizi[7]).getKullanim())){
            jButton8.setVisible(false);
        }
        
        if(list.get(dizi[8]).kullanildiMi(list.get(dizi[8]).getKullanim())){
            jButton9.setVisible(false);
        }
        
        if(list.get(dizi[9]).kullanildiMi(list.get(dizi[9]).getKullanim())){
            jButton10.setVisible(false);
        }
    sayac2++;
        sonucsayac++;
         if(sonucsayac==5){
             jButtonsonuç.setVisible(true);
         }
    }//GEN-LAST:event_jButton28ActionPerformed
    }
    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        System.out.println("Size"+Bot2.liste.size());
        System.out.println("o nun degeri"+o);
        if(o==Bot2.liste.size() || t>=5){
       o--;
          t++;
          p++;
           Random rnd=new Random();
         int z=rnd.nextInt(3);
         while(Bot2.liste.get(z).kullanildiMi2(Bot2.liste.get(z).getKullanim2())){
             z=rnd.nextInt(3);
         }
         if(oyuncu.liste.get(4).getDamage()>Bot2.liste.get(z).getDamage()){
             oyuncu.setSkor();
         }
         else if(oyuncu.liste.get(4).getDamage()==Bot2.liste.get(z).getDamage()){
             
         }
         else{
             Bot2.setSkor();
             
         }
         oyuncu.SkorGoster();
         Bot2.SkorGoster();
         Bot2.liste.get(z).setKullanim2();
         oyuncu.liste.get(4).setKullanim2();
         if(z==0){
             jButton33.setVisible(false);
         }
         if(z==1){
             jButton34.setVisible(false);
         }
         if(z==2){
             jButton35.setVisible(false);
         }
         sayac--;
         jButton29.setVisible(false);
          jButtonarea1.setIcon(new javax.swing.ImageIcon(oyuncu.liste.get(4).getDosyayolu()));
        jButtonarea2.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
        jButtonarea1.setVisible(true);
        jButtonarea2.setVisible(true);
        
        int y1=0;
    if(son<2){
        y1=rnd.nextInt(10);
    while(list.get(y1).kullanildiMi(list.get(y1).getKullanim())){
        y1=rnd.nextInt(10);
    }
    }
    
    System.out.println("y1-->" +y1);
    if(son<=1){
         Bot2.liste.set(z,list.get(y1));
   
    Bot2.liste.get(z).setKullanim();
    
    son++;
    if(z==0){
             jButton33.setVisible(true);
             jButton33.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
         if(z==1){
             jButton34.setVisible(true);
              jButton34.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
             
         }
         if(z==2){
             jButton35.setVisible(true);
              jButton35.setIcon(new javax.swing.ImageIcon(Bot2.liste.get(z).getDosyayolu()));
         }
   }
     
  
    
         if(list.get(dizi[0]).kullanildiMi(list.get(dizi[0]).getKullanim())){
            jButton11.setVisible(false);
        }
        
        if(list.get(dizi[1]).kullanildiMi(list.get(dizi[1]).getKullanim())){
            jButton12.setVisible(false);
        }
        
        if(list.get(dizi[2]).kullanildiMi(list.get(dizi[2]).getKullanim())){
            jButton3.setVisible(false);
        }
        
        if(list.get(dizi[3]).kullanildiMi(list.get(dizi[3]).getKullanim())){
            jButton4.setVisible(false);
        }
        
        if(list.get(dizi[4]).kullanildiMi(list.get(dizi[4]).getKullanim())){
            jButton5.setVisible(false);
        }
        
        if(list.get(dizi[5]).kullanildiMi(list.get(dizi[5]).getKullanim())){
            jButton6.setVisible(false);
        }
        
        if(list.get(dizi[6]).kullanildiMi(list.get(dizi[6]).getKullanim())){
            jButton7.setVisible(false);
        }
        
        if(list.get(dizi[7]).kullanildiMi(list.get(dizi[7]).getKullanim())){
            jButton8.setVisible(false);
        }
        
        if(list.get(dizi[8]).kullanildiMi(list.get(dizi[8]).getKullanim())){
            jButton9.setVisible(false);
        }
        
        if(list.get(dizi[9]).kullanildiMi(list.get(dizi[9]).getKullanim())){
            jButton10.setVisible(false);
        }
    sayac2++;
        sonucsayac++;
         if(sonucsayac==5){
             jButtonsonuç.setVisible(true);
         }
    }//GEN-LAST:event_jButton29ActionPerformed
    }
    private void jButtonsonuçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsonuçActionPerformed
        if(oyuncu.getSkor()>Bot2.getSkor()){
            System.out.println("Oyuncu kazandı");
            JOptionPane.showMessageDialog(this,oyuncu.getOyuncuAdi()+"kullanıcısının skoru: "+oyuncu.getSkor()+"\nBotun skoru: "+Bot2.getSkor()+"\nKazanan ==> "+oyuncu.getOyuncuAdi());
        }
        else if(oyuncu.getSkor()==Bot2.getSkor()){
            System.out.println("Berabere");
            JOptionPane.showMessageDialog(this,oyuncu.getOyuncuAdi()+"kullanıcısının skoru: "+oyuncu.getSkor()+"\nBotun skoru: "+Bot2.getSkor()+"\nBerabere");
        }
        else{
            System.out.println("Bot kazandı");
            JOptionPane.showMessageDialog(this,oyuncu.getOyuncuAdi()+"kullanıcısının skoru: "+oyuncu.getSkor()+"\nBotun skoru: "+Bot2.getSkor()+"\nKazanan ==> Bot ");
        }
        exit(0);
    }//GEN-LAST:event_jButtonsonuçActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFkvsb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFkvsb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFkvsb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFkvsb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFkvsb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    private javax.swing.JButton jButton20;
    public javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton30;
    public javax.swing.JButton jButton31;
    public javax.swing.JButton jButton32;
    public javax.swing.JButton jButton33;
    public javax.swing.JButton jButton34;
    public javax.swing.JButton jButton35;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JButton jButtonarea1;
    public javax.swing.JButton jButtonarea2;
    public javax.swing.JButton jButtonsonuç;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sil;
    public javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
